### ISSUE TITLE
Print does not print all rows

### ISSUE THREAD

**Issue by dncap** [unosquare/tubular-common#346]
**Describe the bug**
Given: A user wants to print the data table.
When: A user clicks on the default print icon.
Then: All rows except the last one is showing up within the print view.

**To Reproduce**
1. Click on the print
2. View missing data rows within the print preview

**Expected behavior**
A user should be allowed to print all rows.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: Most Updated

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kadosh** [comment]
Issue has been fixed on tubular-react 4.2.10 @ccastello , @Hector26 , @dncap
